name: build

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [26.x]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }} 🏎
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install 📶
        run: |
          yarn
        env:
          CI: true

      - name: Lint 💚
        run: |
          yarn lint
        env:
          CI: true

      - name: Test 🧪
        run: yarn test

      - name: Build 🛠
        run: |
          yarn build
        env:
          CI: true
          VITE_LDS_KEY: ${{ secrets.VITE_LDS_KEY }}

      - name: Deploy Client ⚛
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
